"""A repository may generate its own index.

Check 3 byte-compares the committed index against a fresh render, which only
works when this tool wrote the file. A repository with its own generator — same
slot, its own format, usually predating this standard — fails that comparison
forever, and the only escapes are abandoning a working generator or switching
the check off. Declaring `docmap: own` keeps a real check instead: the index
must not predate what it indexes.
"""

import unittest

from fixtures import TempRepo, by_check, ctx_for
from project_standard import docmap, runner


def _own(r):
    """Give the repo a foreign index and declare it."""
    contract = (r.dir / "CLAUDE.md").read_text().replace(
        "critical-paths:", "docmap: own\ncritical-paths:")
    r.write("CLAUDE.md", contract)
    r.write("docs/DOCMAP.md",
            "# Index\n\nGenerated by scripts/docmap.py — not by this tool.\n")


class TestForeignIndex(unittest.TestCase):

    def test_a_foreign_index_fails_the_byte_comparison_by_default(self):
        # The behaviour that made this necessary: undeclared, it is red and
        # stays red however current the index actually is.
        with TempRepo() as r:
            r.standard_repo()
            r.write("docs/DOCMAP.md", "# Index\n\nWritten by another tool.\n")
            r.commit()
            self.assertTrue(by_check(runner.run(r.dir).findings, "3"))

    def test_declaring_it_own_stops_the_byte_comparison(self):
        with TempRepo() as r:
            r.standard_repo()
            _own(r)
            r.commit()
            self.assertEqual([], by_check(runner.run(r.dir).findings, "3"))

    def test_but_a_stale_foreign_index_is_still_an_error(self):
        # The point is a different check, not no check.
        with TempRepo() as r:
            r.standard_repo()
            _own(r)
            r.commit()
            r.write("docs/PROJECT_MAP.md", "# Code map\n\nchanged after the index\n")
            r.commit("docs: change an indexed document")
            hits = by_check(runner.run(r.dir).findings, "3")
            self.assertTrue(hits, "a foreign index that predates its documents passed")
            self.assertIn("indexes", hits[0].message)

    def test_regenerating_the_foreign_index_clears_it(self):
        with TempRepo() as r:
            r.standard_repo()
            _own(r)
            r.commit()
            r.write("docs/PROJECT_MAP.md", "# Code map\n\nchanged\n")
            r.commit("docs: change an indexed document")
            r.write("docs/DOCMAP.md", "# Index\n\nRegenerated by scripts/docmap.py\n")
            r.commit("docs: reindex")
            self.assertEqual([], by_check(runner.run(r.dir).findings, "3"))

    def test_the_declaration_is_in_the_contract_grammar(self):
        from project_standard.contract import KNOWN_KEYS
        self.assertIn("docmap", KNOWN_KEYS)

    def test_the_tools_own_index_is_still_byte_compared_when_undeclared(self):
        # The default must not soften: an index this tool wrote is still held
        # to an exact match.
        with TempRepo() as r:
            r.standard_repo()
            r.commit()
            ctx = ctx_for(r.dir)
            r.write("docs/DOCMAP.md", docmap.render(ctx))
            r.commit("docs: index")
            self.assertEqual([], by_check(runner.run(r.dir).findings, "3"))
            r.write("docs/DOCMAP.md", docmap.render(ctx) + "\nstray line\n")
            r.commit("docs: corrupt the index")
            self.assertTrue(by_check(runner.run(r.dir).findings, "3"))


if __name__ == "__main__":
    unittest.main()
