"""A critical path may declare what must be READ before editing it.

`critical-paths` says "be careful here". It does not say where the knowledge lives, and that is the
half a newcomer — or an agent — cannot guess: the reference lookups a project depends on are
discoverable only if you already know they exist, so the person most likely to miss one is editing
exactly the code that needed it.

The checker cannot make anyone read a document. What it can do is stop a declared reference from
quietly ceasing to be one, which happens two ways and both are worse than never declaring it: the
file moves, so the promise points at nothing; or it drifts, so the promise points at something wrong
and is believed. An undeclared reference misleads nobody.
"""

import unittest

from fixtures import TempRepo, by_check, ctx_for
from project_standard import artifacts

GENERATED = "# Field map\n\n**Generated by `scripts/fieldmap.py` — do not hand-edit.**\n"
STAMPED = "# Ownership register\n\n**Last reviewed:** 2026-01-01\n"
UNMARKED = "# Some notes\n\nProse with no provenance of any kind.\n"


def _repo(tmp, entries, files=()):
    """A standard repo whose contract carries `entries` as its critical-paths list."""
    r = tmp.standard_repo()
    for rel, body in files:
        r.write(rel, body)
    r.write("src/integrations/client.ts", "export const q = 1\n")
    r.write("CLAUDE.md", r.contract_block(**{"critical-paths": entries}))
    r.commit()
    return r


class TestDeclaredReferences(unittest.TestCase):

    def test_a_bare_path_list_declares_nothing_and_is_never_flagged(self):
        """Adoption must cost nothing: the overwhelmingly common contract is unchanged."""
        with TempRepo() as tmp:
            _repo(tmp, ["src/integrations/"])
            out = artifacts.check(ctx_for(tmp.dir))
            self.assertEqual(by_check(out, "20a"), [])
            self.assertEqual(by_check(out, "20b"), [])

    def test_a_reference_that_does_not_exist_is_an_error(self):
        """The promise points at nothing. Whoever was told to read it before editing cannot."""
        with TempRepo() as tmp:
            _repo(tmp, ["path: src/integrations/\n    reference: docs/reference/GONE.md"])
            hits = by_check(artifacts.check(ctx_for(tmp.dir)), "20a")
            self.assertEqual(len(hits), 1, "a missing required-reading file must be reported")
            self.assertIn("GONE.md", hits[0].message)

    def test_a_generated_reference_is_accepted_without_a_review_stamp(self):
        """Generated references are the common case for this key and nobody reviews them.

        Demanding a `Last reviewed:` date would train projects to hand-write one onto a file whose
        own header says do not hand-edit — teaching the exact habit the stamp exists to detect.
        """
        with TempRepo() as tmp:
            _repo(tmp, ["path: src/integrations/\n    reference: docs/reference/FIELD_MAP.md"],
                  files=[("docs/reference/FIELD_MAP.md", GENERATED)])
            out = artifacts.check(ctx_for(tmp.dir))
            self.assertEqual(by_check(out, "20a"), [])
            self.assertEqual(by_check(out, "20b"), [])

    def test_a_stamped_reference_is_accepted(self):
        with TempRepo() as tmp:
            _repo(tmp, ["path: src/integrations/\n    reference: docs/OWNERS.md"],
                  files=[("docs/OWNERS.md", STAMPED)])
            self.assertEqual(by_check(artifacts.check(ctx_for(tmp.dir)), "20b"), [])

    def test_a_reference_with_no_provenance_is_a_warning_not_an_error(self):
        """It exists, so the promise is keepable — a reader just cannot tell whether to trust it.

        A warning rather than an error on purpose: the document may be perfectly current, and
        failing a gate over a missing stamp would push projects to stop declaring references at all,
        which loses more than it gains.
        """
        with TempRepo() as tmp:
            _repo(tmp, ["path: src/integrations/\n    reference: docs/NOTES.md"],
                  files=[("docs/NOTES.md", UNMARKED)])
            out = artifacts.check(ctx_for(tmp.dir))
            self.assertEqual(by_check(out, "20a"), [])
            hits = by_check(out, "20b")
            self.assertEqual(len(hits), 1)
            self.assertEqual(hits[0].severity, "warn")

    def test_a_declared_path_is_still_checked_for_existence(self):
        """The mapping form must not smuggle a path past check 20."""
        with TempRepo() as tmp:
            _repo(tmp, ["path: src/deleted/\n    reference: docs/reference/FIELD_MAP.md"],
                  files=[("docs/reference/FIELD_MAP.md", GENERATED)])
            hits = by_check(artifacts.check(ctx_for(tmp.dir)), "20")
            self.assertTrue(any("src/deleted/" in h.message for h in hits),
                            "a mapping entry's path must face the same existence check as a bare one")


if __name__ == "__main__":
    unittest.main()
